crud/urls.py
from django.contrib import admin
from django.urls import path
from employee import views
from django.conf import settings 
from django.conf.urls.static import static
 
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
	path('',views.home),
    path('rr',views.registration),
    path('login',views.login),
    path('check',views.check),
    path('logout',views.log_out),
	path('search',views.search)	
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):  
	eid = models.CharField(max_length=20)  
	ename = models.CharField(max_length=100)  
	eemail = models.EmailField()  
	econtact = models.CharField(max_length=15) 
	eimage=models.ImageField(upload_to="emp",null=True)
	class Meta:  
		db_table = "employee"  

employee/forms.py
from django import forms  
from employee.models import Employee  
from django.contrib.auth.models import User
from django.core.validators import validate_email
from .models import *


class userform(forms.ModelForm):
	username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter UserName'}),required=True,max_length=30)

	email=forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter Email'}),required=True,max_length=30)
	
	first_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter First Name'}),required=True,max_length=30)
	
	last_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Last Name'}),required=True,max_length=30)
	
	password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Password'}),required=True,max_length=30)
	
	confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Confirm Password'}),required=True,max_length=30)
	
	class Meta():
		model=User
		fields=['username','email','first_name','last_name','password','confirm_password']

	def clean_email(self):
		email=self.cleaned_data['email']
		try:
			ma=validate_email(email)
		except:
			raise forms.ValidationError("Email is not valid")
		return email
	def clean_confirm_password(self):
		p=self.cleaned_data['password']
		cp=self.cleaned_data['confirm_password']
		if(p!=cp):
			raise forms.ValidationError("Confirm Password and password must be same")
		else:
			if(len(p)<8):
				raise forms.ValidationError("password must be atleast 8 character")
			if(p.isdigit()):
				raise forms.ValidationError("password must contains atleast a character")

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

employee/views.py
from django.shortcuts import render, redirect ,HttpResponse
from employee.forms import *  
from employee.models import Employee  
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from crud import settings
from django.contrib import messages

# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST,request.FILES)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  
@login_required(login_url='/login')
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  

@login_required(login_url='/login')
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})

@login_required(login_url='/login')  
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST,request.FILES, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  

@login_required(login_url='/login')
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

def home(request):
	return render(request,'home.html')
	
def registration(request):
	if request.method=='POST':
		form1=userform(request.POST)
		if form1.is_valid():
			username=form1.cleaned_data['username']
			first_name=form1.cleaned_data['first_name']
			last_name=form1.cleaned_data['last_name']
			email=form1.cleaned_data['email']
			password=form1.cleaned_data['password']
			subject="Confirmation mail"
			msg="dear sir/maam,thank you for more details visit :"
			send_mail(subject,msg,settings.EMAIL_HOST_USER,[email])
			User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)
			return redirect("/login")
	else:
		form1=userform()
	return render(request,'regis.html',{'frm':form1})

def login(request):
    return render(request,"login.html")

def check(request):
    username= request.POST['username']
    password=request.POST['password']
    user =authenticate(username= username , password=password)
    print(user)
    if user is not None:
        auth.login(request,user)
        return redirect("/emp")
    else:
        return HttpResponse('<h1> invalid </h1>')

def log_out(request):  # we use log_out like this beacuse we have predefined function logout already
    auth.logout(request)
    return render(request,'login.html')
	
def search(request):
	if request.method=='POST':
		squery= request.POST['search_box']
		if squery is not None:
			s=Employee.objects.filter(ename__icontains=squery)
			if s:
				return render(request,'search.html',{'q':s})
			else:
				return HttpResponse('<h1> not found </h1>')
		else:
			return redirect('/show')
	return redirect('/')
	

employee/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
	<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Image:</label>  
    <div class="col-sm-4">  
        <input type="file" name="eimage" id="id_eimage"  value="{{ employee.eimage }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

employee/templates/home.html
{% load static %}
<html>
		<body background="{% static 'image.jpg' %}">
			<form action="/rr" method=get >
			{% csrf_token %}
		<center><button type=submit><h1>Submit</h1></button></center>
			</form>
		</body>
</html>

employee/templates/index.html
{% load static %}
<html>
<head>  
    <title>Index</title>  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body background="{% static 'image.jpg' %}" >  
<form method="POST" class="post-form" action="/emp" enctype="multipart/form-data">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>
	 <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Image:</label> 
	<div class="col-sm-4">
	  {{ form.eimage }}
	</div>
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
<form action="/logout">
  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">LOG OUT</button>  
    </div>
  </div>
</form>
<form action="/show">
  <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">SHOW DETAILS</button>  
    </div>
  </div>
</form>
</body>  
</html>  

employee/templates/login.html
       <div style="width:300px;height:150px;margin-left:350px">
		<h2 style="width:300px;height:40px;background-color:gray;font-family:stencil;font-size:25px;padding-top:15px"><center>Login</center></h2>
		<form method="post" action="/check">{% csrf_token %}
		    <table>
			   <tr height=50px><th>Username:</th>
			   <td><input type="text" name="username" value="" id="username"></td></tr>
			   <tr height=50px><th>Password:</th>
			   <td><input type="password" name="password" value="" id="password"></td></tr>
			</table><br>
            <input type="submit" value="Login" />
            
	    </form>
     <a href="/rr">Register</a>
	 </div>
 

employee/templates/regis.html
{% load static %}
<html>
<head>
	<title>Sample</title>
	<link rel="stylesheet"  href="{% static 'style.css'%}"/>
</head>
<body background="{% static 'image.jpg' %}">
<h1>User Registration Form</h1>


<form method="POST" action="" class="col-md-5">  
	{%csrf_token%}
	{{frm.as_p}}
	<button type="submit">Submit</button>

</form>
<button><center><a href="/login">LOGIN</a></center></button>
</body>
</html>

employee/templates/search.html
<html>
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body>  
<form action='/search' method='POST'>
	{%csrf_token %}
	<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Enter name :</label>  
    <div class="col-sm-4">  
    <input class='text' name='search_box' placeholder='enter employee name : '></input>	
    </div>  
	</div>
	<div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type='submit' class="btn btn-primary">search</button>	
    </div> 
	</form>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in q %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  

<a href="/logout">LOGOUT</a>
</body>  
</html>  

employee/templates/show.html
<html>
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body>  
<form action='/search' method='POST'>
	{%csrf_token %}
	<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Enter name :</label>  
    <div class="col-sm-4">  
    <input class='text' name='search_box' placeholder='enter employee name : '></input>	
    </div>  
	</div>
	<div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type='submit' class="btn btn-primary">search</button>	
    </div> 
	</form>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th> 
	    <th>Employee Image</th>
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>
        <td><img src="media/{{employee.eimage}}" width=300px/></td>		
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  

<a href="/logout">LOGOUT</a>
</body>  
</html>  